// Demo catalog content for Global Rotan. All business facts are placeholders.

export const TONE_COLORS = {
  honey: { name_en: 'Natural Honey', name_id: 'Madu Natural', hex: '#C89B5E', family: 'honey' },
  walnut: { name_en: 'Walnut Brown', name_id: 'Cokelat Walnut', hex: '#7E5636', family: 'brown' },
  whitewash: { name_en: 'Whitewash', name_id: 'Putih Whitewash', hex: '#E4D8C3', family: 'white' },
  black: { name_en: 'Espresso Black', name_id: 'Hitam Espresso', hex: '#37322D', family: 'black' },
  sand: { name_en: 'Sand Grey', name_id: 'Abu Pasir', hex: '#A89F92', family: 'grey' },
  charcoal: { name_en: 'Charcoal', name_id: 'Arang', hex: '#58534D', family: 'grey' },
  natural: { name_en: 'Natural Cane', name_id: 'Rotan Natural', hex: '#D2AE78', family: 'natural' },
};

export const CATEGORIES = [
  {
    slug: 'chairs',
    name_en: 'Chairs',
    name_id: 'Kursi',
    description_en: 'Lounge, dining and accent chairs woven from rattan and cane.',
    description_id: 'Kursi santai, kursi makan, dan kursi aksen dari rotan dan anyaman cane.',
  },
  {
    slug: 'tables',
    name_en: 'Tables',
    name_id: 'Meja',
    description_en: 'Coffee, side and dining tables with rattan and teak details.',
    description_id: 'Meja kopi, meja samping, dan meja makan dengan detail rotan dan jati.',
  },
  {
    slug: 'sofas',
    name_en: 'Sofas',
    name_id: 'Sofa',
    description_en: 'Two- and three-seater rattan sofas with removable cushions.',
    description_id: 'Sofa rotan dua dan tiga dudukan dengan bantalan yang dapat dilepas.',
  },
  {
    slug: 'dining-sets',
    name_en: 'Dining Sets',
    name_id: 'Set Meja Makan',
    description_en: 'Coordinated tables and chairs for homes, cafés and restaurants.',
    description_id: 'Paduan meja dan kursi untuk rumah, kafe, dan restoran.',
  },
  {
    slug: 'outdoor-furniture',
    name_en: 'Outdoor Furniture',
    name_id: 'Furnitur Outdoor',
    description_en: 'Weather-ready synthetic rattan for terraces, pools and resorts.',
    description_id: 'Rotan sintetis tahan cuaca untuk teras, kolam renang, dan resor.',
  },
  {
    slug: 'home-accessories',
    name_en: 'Home Accessories',
    name_id: 'Aksesori Rumah',
    description_en: 'Pendant lamps, baskets and mirrors that complete a room.',
    description_id: 'Lampu gantung, keranjang, dan cermin untuk melengkapi ruangan.',
  },
  {
    slug: 'custom-furniture',
    name_en: 'Custom Furniture',
    name_id: 'Furnitur Custom',
    description_en: 'Made-to-measure rattan pieces for hospitality and retail projects.',
    description_id: 'Furnitur rotan sesuai ukuran untuk proyek hospitality dan retail.',
  },
];

export const COLLECTIONS = [
  {
    slug: 'kawi',
    name_en: 'Kawi Collection',
    name_id: 'Koleksi Kawi',
    tagline_en: 'Classic natural rattan with teak accents',
    tagline_id: 'Rotan alami klasik dengan aksen jati',
    description_en:
      'Named after the volcanic highlands of East Java, Kawi pairs steam-bent rattan frames with cane webbing and solid teak. Warm, generous proportions for living and dining rooms.',
    description_id:
      'Terinspirasi dari dataran tinggi Kawi di Jawa Timur, koleksi ini memadukan rangka rotan yang dibentuk dengan uap, anyaman cane, dan kayu jati solid. Proporsi yang hangat dan lapang untuk ruang keluarga dan ruang makan.',
    is_featured: true,
  },
  {
    slug: 'senja',
    name_en: 'Senja Collection',
    name_id: 'Koleksi Senja',
    tagline_en: 'Light, modern cane pieces',
    tagline_id: 'Furnitur cane yang ringan dan modern',
    description_en:
      'Senja — “dusk” in Indonesian — is a lighter, contemporary line with slim frames and open cane panels that suit cafés, apartments and boutique hotels.',
    description_id:
      'Senja adalah lini kontemporer yang lebih ringan dengan rangka ramping dan panel cane terbuka, cocok untuk kafe, apartemen, dan hotel butik.',
    is_featured: true,
  },
  {
    slug: 'nusa',
    name_en: 'Nusa Collection',
    name_id: 'Koleksi Nusa',
    tagline_en: 'Outdoor comfort for resorts and terraces',
    tagline_id: 'Kenyamanan outdoor untuk resor dan teras',
    description_en:
      'Nusa uses UV-stabilised synthetic rattan over aluminium frames with quick-dry cushions — designed for poolsides, beach clubs and garden terraces.',
    description_id:
      'Nusa menggunakan rotan sintetis tahan UV di atas rangka aluminium dengan bantalan cepat kering — dirancang untuk tepi kolam, beach club, dan teras taman.',
    is_featured: true,
  },
];

const finishingNatural = [
  { en: 'Natural clear matte', id: 'Natural bening doff' },
  { en: 'Honey stain', id: 'Pewarna madu' },
  { en: 'Walnut stain', id: 'Pewarna walnut' },
];
const finishingOutdoor = [
  { en: 'Standard outdoor cushion', id: 'Bantalan outdoor standar' },
  { en: 'Quick-dry foam upgrade', id: 'Upgrade busa cepat kering' },
];

const careNatural = {
  care_en:
    'Dust weekly with a soft brush. Keep away from prolonged direct sunlight, rain and heaters. Wipe spills with a slightly damp cloth and dry in the shade. Re-apply clear wax once a year to keep the fibre supple.',
  care_id:
    'Bersihkan debu setiap minggu dengan kuas lembut. Hindarkan dari sinar matahari langsung yang lama, hujan, dan pemanas. Lap tumpahan dengan kain sedikit lembap lalu keringkan di tempat teduh. Oleskan wax bening setahun sekali agar serat tetap lentur.',
};
const careOutdoor = {
  care_en:
    'Rinse with fresh water and mild soap, especially near the sea or chlorinated pools. Store cushions or use covers during heavy rain. Aluminium frames do not rust; tighten feet caps seasonally.',
  care_id:
    'Bilas dengan air bersih dan sabun lembut, terutama di dekat laut atau kolam berklorin. Simpan bantalan atau gunakan penutup saat hujan lebat. Rangka aluminium tidak berkarat; kencangkan kaki penyangga secara berkala.',
};

export const PRODUCTS = [
  {
    slug: 'kawi-lounge-chair',
    sku: 'GR-CH-001',
    name_en: 'Kawi Lounge Chair',
    name_id: 'Kursi Santai Kawi',
    short_en: 'A low, generous lounge chair with a cane-webbed back and hand-bound rattan arms.',
    short_id: 'Kursi santai rendah dan lapang dengan sandaran anyaman cane dan lengan rotan yang diikat tangan.',
    desc_en:
      'The Kawi Lounge Chair is built around a steam-bent rattan frame, finished with a curved cane-webbed backrest and a thick removable seat cushion.\n\nIts wide arms and relaxed seat angle make it a comfortable reading chair at home and a durable accent piece for hotel lobbies and villas.',
    desc_id:
      'Kursi Santai Kawi dibuat dari rangka rotan yang dibentuk dengan uap, dilengkapi sandaran melengkung beranyaman cane dan bantalan duduk tebal yang dapat dilepas.\n\nLengan yang lebar dan sudut duduk yang santai membuatnya nyaman untuk membaca di rumah sekaligus menjadi kursi aksen yang awet untuk lobi hotel dan vila.',
    category: 'chairs',
    collection: 'kawi',
    price: 385,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'fabric_cushion'],
    material_en: 'Grade A natural rattan poles, hand-woven cane webbing, cotton-linen cushion cover',
    material_id: 'Batang rotan alami grade A, anyaman cane tangan, sarung bantal katun-linen',
    finishing_en: 'Water-based clear matte lacquer',
    finishing_id: 'Lapisan lacquer bening doff berbasis air',
    finishing_options: finishingNatural,
    usage: 'indoor',
    dims: [78, 82, 76],
    seat: 40,
    weight: 9.5,
    moq: 2,
    lead: [4, 6],
    availability: 'ready_stock',
    flags: { is_featured: true, is_best_seller: true },
    tones: ['honey', 'walnut', 'whitewash'],
    sizes: [
      { label_en: 'Standard', label_id: 'Standar', dims: [78, 82, 76], adj: 0 },
      { label_en: 'Wide', label_id: 'Lebar', dims: [90, 86, 76], adj: 45 },
    ],
    unavailable: [['whitewash', 'Wide']],
    ...careNatural,
  },
  {
    slug: 'senja-cane-dining-chair',
    sku: 'GR-CH-002',
    name_en: 'Senja Cane Dining Chair',
    name_id: 'Kursi Makan Cane Senja',
    short_en: 'A slim dining chair with open cane back and seat, light enough to move with one hand.',
    short_id: 'Kursi makan ramping dengan sandaran dan dudukan cane terbuka, cukup ringan diangkat satu tangan.',
    desc_en:
      'Senja brings a café-style silhouette to the dining table. The frame is made from solid rattan with a tight cane weave on the seat and back, and an optional fabric seat pad.\n\nA practical choice for restaurants that need comfortable, stackable-looking chairs with a natural feel.',
    desc_id:
      'Senja menghadirkan siluet ala kafe di meja makan. Rangkanya dari rotan solid dengan anyaman cane rapat pada dudukan dan sandaran, serta bantalan kain opsional.\n\nPilihan praktis untuk restoran yang membutuhkan kursi nyaman dengan nuansa alami.',
    category: 'chairs',
    collection: 'senja',
    price: 168,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane'],
    material_en: 'Solid rattan frame with natural cane webbing',
    material_id: 'Rangka rotan solid dengan anyaman cane alami',
    finishing_en: 'Clear matte or black stain',
    finishing_id: 'Bening doff atau pewarna hitam',
    finishing_options: [],
    usage: 'indoor',
    dims: [46, 52, 88],
    seat: 46,
    weight: 4.2,
    moq: 6,
    lead: [5, 7],
    availability: 'made_to_order',
    flags: { is_new: true },
    tones: ['natural', 'black'],
    sizes: [
      { label_en: 'Armless', label_id: 'Tanpa Lengan', dims: [46, 52, 88], adj: 0 },
      { label_en: 'With Armrest', label_id: 'Dengan Lengan', dims: [54, 54, 88], adj: 24 },
    ],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'nusa-outdoor-armchair',
    sku: 'GR-OD-001',
    name_en: 'Nusa Outdoor Armchair',
    name_id: 'Kursi Lengan Outdoor Nusa',
    short_en: 'Deep-seated armchair in UV-stable synthetic rattan with quick-dry cushions.',
    short_id: 'Kursi lengan berdudukan dalam dari rotan sintetis tahan UV dengan bantalan cepat kering.',
    desc_en:
      'Designed for terraces and poolside lounges, the Nusa Armchair wraps a rust-free aluminium frame in round synthetic rattan fibre.\n\nThe cushions use outdoor fabric with removable covers, making housekeeping simple for resorts and beach clubs.',
    desc_id:
      'Dirancang untuk teras dan area santai tepi kolam, Kursi Lengan Nusa membalut rangka aluminium anti karat dengan serat rotan sintetis bulat.\n\nBantalannya menggunakan kain outdoor dengan sarung yang dapat dilepas, sehingga mudah dirawat oleh tim resor dan beach club.',
    category: 'outdoor-furniture',
    collection: 'nusa',
    price: 295,
    price_type: 'estimated',
    materials: ['synthetic_rattan', 'aluminium', 'fabric_cushion'],
    material_en: 'Round 7 mm HDPE synthetic rattan over powder-coated aluminium',
    material_id: 'Rotan sintetis HDPE bulat 7 mm di atas aluminium powder coating',
    finishing_en: 'UV-stabilised fibre, outdoor acrylic fabric',
    finishing_id: 'Serat tahan UV, kain akrilik outdoor',
    finishing_options: finishingOutdoor,
    usage: 'outdoor',
    dims: [80, 84, 78],
    seat: 42,
    weight: 11,
    moq: 4,
    lead: [4, 6],
    availability: 'ready_stock',
    flags: {},
    tones: ['sand', 'charcoal', 'honey'],
    sizes: [],
    unavailable: [],
    ...careOutdoor,
  },
  {
    slug: 'kawi-three-seater-sofa',
    sku: 'GR-SF-001',
    name_en: 'Kawi Three-Seater Sofa',
    name_id: 'Sofa Tiga Dudukan Kawi',
    short_en: 'A relaxed rattan sofa with cane back panel and feather-blend cushions.',
    short_id: 'Sofa rotan santai dengan panel sandaran cane dan bantalan campuran bulu.',
    desc_en:
      'The Kawi Sofa balances a strong rattan frame with a light, open cane back. Seat and back cushions are zipped for easy cleaning or re-covering in your own fabric.\n\nAvailable in two lengths for living rooms, hotel suites and lounge areas.',
    desc_id:
      'Sofa Kawi memadukan rangka rotan yang kokoh dengan sandaran cane yang ringan dan terbuka. Bantalan dudukan dan sandaran menggunakan ritsleting agar mudah dibersihkan atau diganti dengan kain pilihan Anda.\n\nTersedia dalam dua panjang untuk ruang keluarga, suite hotel, dan area lounge.',
    category: 'sofas',
    collection: 'kawi',
    price: 1250,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'fabric_cushion'],
    material_en: 'Natural rattan frame, cane back panel, foam and fibre cushions',
    material_id: 'Rangka rotan alami, panel sandaran cane, bantalan busa dan serat',
    finishing_en: 'Water-based clear matte lacquer',
    finishing_id: 'Lapisan lacquer bening doff berbasis air',
    finishing_options: finishingNatural,
    usage: 'indoor',
    dims: [210, 88, 80],
    seat: 42,
    weight: 32,
    moq: 1,
    lead: [6, 8],
    availability: 'made_to_order',
    flags: { is_featured: true },
    tones: ['honey', 'walnut'],
    sizes: [
      { label_en: '2-Seater', label_id: '2 Dudukan', dims: [160, 88, 80], adj: -280 },
      { label_en: '3-Seater', label_id: '3 Dudukan', dims: [210, 88, 80], adj: 0 },
    ],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'senja-round-coffee-table',
    sku: 'GR-TB-001',
    name_en: 'Senja Round Coffee Table',
    name_id: 'Meja Kopi Bundar Senja',
    short_en: 'Solid teak top on a woven rattan drum base.',
    short_id: 'Daun meja jati solid di atas kaki drum anyaman rotan.',
    desc_en:
      'A sculptural coffee table with a solid teak top and a tapered base woven from rattan core. The drum form hides no joints and adds warmth to minimalist interiors.',
    desc_id:
      'Meja kopi berkarakter dengan daun meja jati solid dan kaki meruncing dari anyaman inti rotan. Bentuk drum tanpa sambungan terlihat menambah kehangatan pada interior minimalis.',
    category: 'tables',
    collection: 'senja',
    price: 420,
    price_type: 'fixed',
    materials: ['natural_rattan', 'teak_wood'],
    material_en: 'Rattan core weave, solid teak top',
    material_id: 'Anyaman inti rotan, daun meja jati solid',
    finishing_en: 'Natural oil on teak, clear matte on rattan',
    finishing_id: 'Minyak natural pada jati, bening doff pada rotan',
    finishing_options: [],
    usage: 'indoor',
    dims: [80, 80, 40],
    seat: null,
    weight: 12,
    moq: 2,
    lead: [3, 5],
    availability: 'ready_stock',
    flags: {},
    tones: ['natural', 'walnut'],
    sizes: [
      { label_en: 'Ø 80 cm', label_id: 'Ø 80 cm', dims: [80, 80, 40], adj: 0 },
      { label_en: 'Ø 100 cm', label_id: 'Ø 100 cm', dims: [100, 100, 40], adj: 90 },
    ],
    unavailable: [['walnut', 'Ø 100 cm']],
    care_en: careNatural.care_en,
    care_id: careNatural.care_id,
  },
  {
    slug: 'nusa-outdoor-dining-set',
    sku: 'GR-DS-001',
    name_en: 'Nusa Outdoor Dining Set',
    name_id: 'Set Makan Outdoor Nusa',
    short_en: 'Outdoor dining table with six synthetic rattan chairs for terraces and restaurants.',
    short_id: 'Meja makan outdoor dengan enam kursi rotan sintetis untuk teras dan restoran.',
    desc_en:
      'A complete outdoor dining setting: a 180 cm table with woven apron and six Nusa side chairs with seat pads. Every piece uses UV-stable fibre over aluminium, suitable for open-air restaurants and villa terraces.',
    desc_id:
      'Set makan outdoor lengkap: meja 180 cm dengan apron anyaman dan enam kursi Nusa dengan bantalan dudukan. Semua bagian menggunakan serat tahan UV di atas aluminium, cocok untuk restoran terbuka dan teras vila.',
    category: 'dining-sets',
    collection: 'nusa',
    price: 2850,
    price_type: 'estimated',
    materials: ['synthetic_rattan', 'aluminium', 'fabric_cushion'],
    material_en: 'Flat synthetic rattan, aluminium frames, outdoor seat pads',
    material_id: 'Rotan sintetis pipih, rangka aluminium, bantalan dudukan outdoor',
    finishing_en: 'UV-stabilised fibre',
    finishing_id: 'Serat tahan UV',
    finishing_options: finishingOutdoor,
    usage: 'outdoor',
    dims: [180, 90, 75],
    seat: 45,
    weight: 68,
    moq: 1,
    lead: [6, 8],
    availability: 'made_to_order',
    flags: { is_featured: true },
    tones: ['sand', 'charcoal'],
    sizes: [
      { label_en: 'Table + 4 chairs', label_id: 'Meja + 4 kursi', dims: [140, 90, 75], adj: -780 },
      { label_en: 'Table + 6 chairs', label_id: 'Meja + 6 kursi', dims: [180, 90, 75], adj: 0 },
    ],
    unavailable: [],
    ...careOutdoor,
  },
  {
    slug: 'kawi-dining-table',
    sku: 'GR-TB-002',
    name_en: 'Kawi Dining Table',
    name_id: 'Meja Makan Kawi',
    short_en: 'Teak dining table with cane apron and bound rattan legs.',
    short_id: 'Meja makan jati dengan apron cane dan kaki rotan yang diikat.',
    desc_en:
      'The Kawi Dining Table combines a solid teak top with a cane-webbed apron and rattan legs joined by traditional bindings. Choose the length that fits your room or restaurant layout.',
    desc_id:
      'Meja Makan Kawi memadukan daun meja jati solid dengan apron beranyaman cane dan kaki rotan yang disambung dengan ikatan tradisional. Pilih panjang yang sesuai dengan ruang atau tata letak restoran Anda.',
    category: 'tables',
    collection: 'kawi',
    price: 980,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'teak_wood'],
    material_en: 'Solid teak top, rattan legs, cane apron',
    material_id: 'Daun meja jati solid, kaki rotan, apron cane',
    finishing_en: 'Natural oil',
    finishing_id: 'Minyak natural',
    finishing_options: [],
    usage: 'indoor',
    dims: [180, 90, 76],
    seat: null,
    weight: 38,
    moq: 1,
    lead: [6, 8],
    availability: 'made_to_order',
    flags: {},
    tones: ['honey', 'walnut'],
    sizes: [
      { label_en: '160 cm', label_id: '160 cm', dims: [160, 90, 76], adj: -120 },
      { label_en: '180 cm', label_id: '180 cm', dims: [180, 90, 76], adj: 0 },
      { label_en: '220 cm', label_id: '220 cm', dims: [220, 100, 76], adj: 260 },
    ],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'segara-canopy-daybed',
    sku: 'GR-OD-002',
    name_en: 'Segara Canopy Daybed',
    name_id: 'Daybed Kanopi Segara',
    short_en: 'A statement outdoor daybed with woven canopy for pools and beach clubs.',
    short_id: 'Daybed outdoor dengan kanopi anyaman untuk kolam renang dan beach club.',
    desc_en:
      'Segara creates a shaded retreat for resorts and private villas. The half-dome canopy and platform are woven from synthetic rattan over aluminium, with a full-length outdoor mattress and scatter cushions.\n\nPricing depends on canopy shape, mattress specification and quantity — contact us for a project quotation.',
    desc_id:
      'Segara menghadirkan tempat bersantai yang teduh untuk resor dan vila pribadi. Kanopi setengah kubah dan alasnya dianyam dari rotan sintetis di atas aluminium, dilengkapi kasur outdoor dan bantal hias.\n\nHarga bergantung pada bentuk kanopi, spesifikasi kasur, dan jumlah — hubungi kami untuk penawaran proyek.',
    category: 'outdoor-furniture',
    collection: 'nusa',
    price: null,
    price_type: 'contact',
    materials: ['synthetic_rattan', 'aluminium', 'fabric_cushion'],
    material_en: 'Synthetic rattan, aluminium frame, outdoor mattress',
    material_id: 'Rotan sintetis, rangka aluminium, kasur outdoor',
    finishing_en: 'UV-stabilised fibre',
    finishing_id: 'Serat tahan UV',
    finishing_options: finishingOutdoor,
    usage: 'outdoor',
    dims: [200, 160, 180],
    seat: null,
    weight: 75,
    moq: 1,
    lead: [8, 10],
    availability: 'made_to_order',
    flags: { is_featured: true },
    tones: ['sand', 'whitewash'],
    sizes: [],
    unavailable: [],
    ...careOutdoor,
  },
  {
    slug: 'anyam-pendant-lamp',
    sku: 'GR-AC-001',
    name_en: 'Anyam Pendant Lamp',
    name_id: 'Lampu Gantung Anyam',
    short_en: 'Hand-woven cane pendant that casts a soft, patterned light.',
    short_id: 'Lampu gantung anyaman cane yang memancarkan cahaya lembut berpola.',
    desc_en:
      'Anyam (“woven”) is a bell-shaped pendant made from cane webbing on a rattan ring. Supplied with a fabric cable and ceiling cup; electrical fittings can be specified for your country.',
    desc_id:
      'Anyam adalah lampu gantung berbentuk lonceng dari anyaman cane pada ring rotan. Dilengkapi kabel kain dan kap plafon; fitting listrik dapat disesuaikan dengan standar negara Anda.',
    category: 'home-accessories',
    collection: 'senja',
    price: 78,
    price_type: 'starting_from',
    materials: ['rattan_cane', 'natural_rattan'],
    material_en: 'Cane webbing, rattan ring, fabric cable',
    material_id: 'Anyaman cane, ring rotan, kabel kain',
    finishing_en: 'Clear matte',
    finishing_id: 'Bening doff',
    finishing_options: [],
    usage: 'indoor',
    dims: [40, 40, 36],
    seat: null,
    weight: 1.2,
    moq: 10,
    lead: [3, 4],
    availability: 'ready_stock',
    flags: { is_new: true },
    tones: ['natural', 'black'],
    sizes: [
      { label_en: 'Small Ø 30', label_id: 'Kecil Ø 30', dims: [30, 30, 28], adj: -18 },
      { label_en: 'Medium Ø 40', label_id: 'Sedang Ø 40', dims: [40, 40, 36], adj: 0 },
      { label_en: 'Large Ø 55', label_id: 'Besar Ø 55', dims: [55, 55, 48], adj: 32 },
    ],
    unavailable: [['black', 'Large Ø 55']],
    care_en: 'Dust with a soft brush. Use LED bulbs up to 10 W to keep the cane cool.',
    care_id: 'Bersihkan debu dengan kuas lembut. Gunakan bola lampu LED maksimal 10 W agar cane tetap sejuk.',
  },
  {
    slug: 'keranjang-storage-basket-set',
    sku: 'GR-AC-002',
    name_en: 'Keranjang Storage Basket Set',
    name_id: 'Set Keranjang Penyimpanan',
    short_en: 'Set of three nesting baskets woven from rattan core.',
    short_id: 'Set tiga keranjang bertumpuk dari anyaman inti rotan.',
    desc_en:
      'Three nesting baskets with bound rims and carry handles, ideal for linen, plants or retail display. Packed nested to save shipping volume.',
    desc_id:
      'Tiga keranjang bertumpuk dengan bibir yang diikat dan pegangan, cocok untuk linen, tanaman, atau display retail. Dikemas bertumpuk untuk menghemat volume pengiriman.',
    category: 'home-accessories',
    collection: null,
    price: 46,
    price_type: 'fixed',
    materials: ['natural_rattan'],
    material_en: 'Rattan core weave',
    material_id: 'Anyaman inti rotan',
    finishing_en: 'Natural or whitewash',
    finishing_id: 'Natural atau whitewash',
    finishing_options: [],
    usage: 'indoor',
    dims: [45, 45, 50],
    seat: null,
    weight: 3,
    moq: 20,
    lead: [2, 4],
    availability: 'ready_stock',
    flags: { is_best_seller: true },
    tones: ['honey', 'whitewash'],
    sizes: [],
    unavailable: [],
  },
  {
    slug: 'senja-two-seater-sofa',
    sku: 'GR-SF-002',
    name_en: 'Senja Two-Seater Sofa',
    name_id: 'Sofa Dua Dudukan Senja',
    short_en: 'Compact cane sofa with slim arms for apartments and hotel rooms.',
    short_id: 'Sofa cane ringkas dengan lengan ramping untuk apartemen dan kamar hotel.',
    desc_en:
      'A compact two-seater with slim rattan arms and a cane back that keeps the silhouette light. Cushions are available in a range of indoor fabrics.',
    desc_id:
      'Sofa dua dudukan yang ringkas dengan lengan rotan ramping dan sandaran cane yang membuat siluetnya tetap ringan. Bantalan tersedia dalam berbagai pilihan kain indoor.',
    category: 'sofas',
    collection: 'senja',
    price: 890,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'fabric_cushion'],
    material_en: 'Rattan frame, cane back, foam cushions',
    material_id: 'Rangka rotan, sandaran cane, bantalan busa',
    finishing_en: 'Clear matte or black stain',
    finishing_id: 'Bening doff atau pewarna hitam',
    finishing_options: [],
    usage: 'indoor',
    dims: [140, 78, 78],
    seat: 43,
    weight: 21,
    moq: 1,
    lead: [5, 7],
    availability: 'made_to_order',
    flags: { is_new: true },
    tones: ['natural', 'black'],
    sizes: [],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'kawi-side-table',
    sku: 'GR-TB-003',
    name_en: 'Kawi Side Table',
    name_id: 'Meja Samping Kawi',
    short_en: 'Hourglass side table with a woven body and teak top.',
    short_id: 'Meja samping berbentuk jam pasir dengan badan anyaman dan daun meja jati.',
    desc_en: 'A compact side table beside a sofa or bed. The woven hourglass base is light but stable, topped with solid teak.',
    desc_id: 'Meja samping ringkas untuk di sisi sofa atau tempat tidur. Kaki anyaman berbentuk jam pasir terasa ringan namun stabil, dengan daun meja jati solid.',
    category: 'tables',
    collection: 'kawi',
    price: 165,
    price_type: 'fixed',
    materials: ['natural_rattan', 'teak_wood'],
    material_en: 'Rattan weave, solid teak top',
    material_id: 'Anyaman rotan, daun meja jati solid',
    finishing_en: 'Natural oil',
    finishing_id: 'Minyak natural',
    finishing_options: [],
    usage: 'indoor',
    dims: [50, 50, 55],
    seat: null,
    weight: 5.5,
    moq: 2,
    lead: [3, 5],
    availability: 'ready_stock',
    flags: {},
    tones: ['honey', 'walnut'],
    sizes: [],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'nusa-sun-lounger',
    sku: 'GR-OD-003',
    name_en: 'Nusa Sun Lounger',
    name_id: 'Kursi Berjemur Nusa',
    short_en: 'Adjustable poolside lounger with wheels and quick-dry mattress.',
    short_id: 'Kursi berjemur tepi kolam yang dapat diatur, dengan roda dan kasur cepat kering.',
    desc_en: 'A five-position sun lounger woven in synthetic rattan over aluminium. Rear wheels make it easy for staff to rearrange pool decks.',
    desc_id: 'Kursi berjemur lima posisi dari anyaman rotan sintetis di atas aluminium. Roda belakang memudahkan staf menata ulang area kolam.',
    category: 'outdoor-furniture',
    collection: 'nusa',
    price: 540,
    price_type: 'estimated',
    materials: ['synthetic_rattan', 'aluminium', 'fabric_cushion'],
    material_en: 'Synthetic rattan, aluminium frame, quick-dry mattress',
    material_id: 'Rotan sintetis, rangka aluminium, kasur cepat kering',
    finishing_en: 'UV-stabilised fibre',
    finishing_id: 'Serat tahan UV',
    finishing_options: finishingOutdoor,
    usage: 'outdoor',
    dims: [200, 72, 36],
    seat: 36,
    weight: 18,
    moq: 4,
    lead: [5, 7],
    availability: 'made_to_order',
    flags: {},
    tones: ['sand', 'charcoal'],
    sizes: [],
    unavailable: [],
    ...careOutdoor,
  },
  {
    slug: 'bespoke-hospitality-lounge-chair',
    sku: 'GR-CU-001',
    name_en: 'Bespoke Hospitality Wing Chair',
    name_id: 'Kursi Wing Hospitality Custom',
    short_en: 'A tall wing chair developed to your dimensions, weave and upholstery.',
    short_id: 'Kursi wing tinggi yang dikembangkan sesuai ukuran, anyaman, dan pelapis pilihan Anda.',
    desc_en:
      'This design is a starting point for hotel lobbies, lounges and suites. Height, width, weave density, frame color and fabric are adjusted to your brief, and a sample can be produced before bulk production.',
    desc_id:
      'Desain ini menjadi titik awal untuk lobi, lounge, dan suite hotel. Tinggi, lebar, kerapatan anyaman, warna rangka, dan kain disesuaikan dengan brief Anda, dan sampel dapat dibuat sebelum produksi massal.',
    category: 'custom-furniture',
    collection: null,
    price: null,
    price_type: 'wholesale_request',
    materials: ['natural_rattan', 'fabric_cushion'],
    material_en: 'Natural rattan weave, upholstery to specification',
    material_id: 'Anyaman rotan alami, pelapis sesuai spesifikasi',
    finishing_en: 'To specification',
    finishing_id: 'Sesuai spesifikasi',
    finishing_options: finishingNatural,
    usage: 'indoor',
    dims: [86, 88, 118],
    seat: 44,
    weight: 16,
    moq: 10,
    lead: [8, 12],
    availability: 'made_to_order',
    flags: {},
    tones: ['honey', 'walnut'],
    sizes: [],
    unavailable: [],
    ...careNatural,
    customization_en:
      'Fully customizable: overall dimensions, seat height, weave pattern (open, closed or cane), frame color, upholstery fabric and branding on packaging. Sampling is available for project orders.',
    customization_id:
      'Dapat dikustomisasi penuh: dimensi keseluruhan, tinggi dudukan, pola anyaman (terbuka, rapat, atau cane), warna rangka, kain pelapis, dan branding pada kemasan. Sampel tersedia untuk pesanan proyek.',
  },
  {
    slug: 'senja-bistro-dining-set',
    sku: 'GR-DS-002',
    name_en: 'Senja Bistro Dining Set',
    name_id: 'Set Makan Bistro Senja',
    short_en: 'Two cane chairs with a woven bistro table for cafés and balconies.',
    short_id: 'Dua kursi cane dengan meja bistro anyaman untuk kafe dan balkon.',
    desc_en: 'A café-ready set of two Senja chairs with seat pads and a Ø 60 cm bistro table. Popular for coffee shops and hotel balconies.',
    desc_id: 'Set siap kafe berisi dua kursi Senja dengan bantalan dudukan dan meja bistro Ø 60 cm. Populer untuk kedai kopi dan balkon hotel.',
    category: 'dining-sets',
    collection: 'senja',
    price: 620,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'teak_wood'],
    material_en: 'Rattan frames, cane webbing, teak table top',
    material_id: 'Rangka rotan, anyaman cane, daun meja jati',
    finishing_en: 'Clear matte or black stain',
    finishing_id: 'Bening doff atau pewarna hitam',
    finishing_options: [],
    usage: 'indoor',
    dims: [60, 60, 74],
    seat: 46,
    weight: 14,
    moq: 2,
    lead: [3, 5],
    availability: 'ready_stock',
    flags: {},
    tones: ['natural', 'black'],
    sizes: [],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'kawi-bar-stool',
    sku: 'GR-CH-003',
    name_en: 'Kawi Bar Stool',
    name_id: 'Kursi Bar Kawi',
    short_en: 'Counter and bar-height stool with cane backrest and footring.',
    short_id: 'Kursi bar dan counter dengan sandaran cane dan pijakan kaki melingkar.',
    desc_en: 'A sturdy stool with a low cane backrest, upholstered seat and bound footring. Choose counter or bar height.',
    desc_id: 'Kursi bar kokoh dengan sandaran cane rendah, dudukan berlapis kain, dan pijakan kaki yang diikat. Tersedia tinggi counter atau bar.',
    category: 'chairs',
    collection: 'kawi',
    price: 210,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane', 'fabric_cushion'],
    material_en: 'Rattan frame, cane backrest, upholstered seat',
    material_id: 'Rangka rotan, sandaran cane, dudukan berlapis kain',
    finishing_en: 'Clear matte',
    finishing_id: 'Bening doff',
    finishing_options: finishingNatural,
    usage: 'indoor',
    dims: [46, 48, 95],
    seat: 75,
    weight: 6,
    moq: 4,
    lead: [4, 6],
    availability: 'made_to_order',
    flags: {},
    tones: ['honey', 'walnut'],
    sizes: [
      { label_en: 'Counter (65 cm)', label_id: 'Counter (65 cm)', dims: [46, 48, 85], adj: 0 },
      { label_en: 'Bar (75 cm)', label_id: 'Bar (75 cm)', dims: [46, 48, 95], adj: 15 },
    ],
    unavailable: [],
    ...careNatural,
  },
  {
    slug: 'lengkung-arched-rattan-mirror',
    sku: 'GR-AC-003',
    name_en: 'Lengkung Arched Rattan Mirror',
    name_id: 'Cermin Lengkung Rotan',
    short_en: 'Arched floor mirror framed in rattan with cane border (draft product).',
    short_id: 'Cermin lantai melengkung berbingkai rotan dengan tepi cane (produk draft).',
    desc_en: 'Draft product used to demonstrate the admin workflow. Publish it from the dashboard when ready.',
    desc_id: 'Produk draft untuk mendemonstrasikan alur kerja admin. Publikasikan dari dashboard jika sudah siap.',
    category: 'home-accessories',
    collection: 'senja',
    price: 240,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane'],
    material_en: 'Rattan frame, cane border, 5 mm mirror glass',
    material_id: 'Bingkai rotan, tepi cane, kaca cermin 5 mm',
    finishing_en: 'Clear matte',
    finishing_id: 'Bening doff',
    finishing_options: [],
    usage: 'indoor',
    dims: [80, 4, 170],
    seat: null,
    weight: 14,
    moq: 2,
    lead: [4, 6],
    availability: 'made_to_order',
    flags: {},
    tones: ['natural'],
    sizes: [],
    unavailable: [],
    status: 'draft',
  },
  {
    slug: 'sekar-rattan-bench',
    sku: 'GR-SF-003',
    name_en: 'Sekar Rattan Bench',
    name_id: 'Bangku Rotan Sekar',
    short_en: 'Discontinued bench kept for reference (archived product).',
    short_id: 'Bangku yang sudah tidak diproduksi, disimpan sebagai referensi (produk arsip).',
    desc_en: 'Archived demo product. Archived products stay in past inquiries but are hidden from the public catalog.',
    desc_id: 'Produk demo yang diarsipkan. Produk arsip tetap tercatat di inquiry lama tetapi disembunyikan dari katalog publik.',
    category: 'sofas',
    collection: null,
    price: 520,
    price_type: 'starting_from',
    materials: ['natural_rattan', 'rattan_cane'],
    material_en: 'Rattan frame, cane seat',
    material_id: 'Rangka rotan, dudukan cane',
    finishing_en: 'Clear matte',
    finishing_id: 'Bening doff',
    finishing_options: [],
    usage: 'indoor',
    dims: [140, 50, 80],
    seat: 44,
    weight: 15,
    moq: 2,
    lead: [4, 6],
    availability: 'made_to_order',
    flags: {},
    tones: ['honey'],
    sizes: [],
    unavailable: [],
    status: 'archived',
  },
];

export const TESTIMONIALS = [
  {
    author_name: 'Sample Customer A',
    author_role_en: 'Boutique hotel owner (demo)',
    author_role_id: 'Pemilik hotel butik (demo)',
    company_name: null,
    country: 'Australia',
    quote_en: 'The lounge chairs arrived well packed and matched the samples we approved. Communication was clear from quotation to delivery.',
    quote_id: 'Kursi santai tiba dengan kemasan rapi dan sesuai dengan sampel yang kami setujui. Komunikasi jelas dari penawaran hingga pengiriman.',
    rating: 5,
  },
  {
    author_name: 'Sample Customer B',
    author_role_en: 'Interior designer (demo)',
    author_role_id: 'Desainer interior (demo)',
    company_name: null,
    country: 'Netherlands',
    quote_en: 'We adjusted seat heights and fabrics for a restaurant project. The team explained the options and lead times honestly.',
    quote_id: 'Kami menyesuaikan tinggi dudukan dan kain untuk proyek restoran. Tim menjelaskan pilihan dan waktu produksi dengan jujur.',
    rating: 5,
  },
  {
    author_name: 'Sample Customer C',
    author_role_en: 'Homeowner (demo)',
    author_role_id: 'Pemilik rumah (demo)',
    company_name: null,
    country: 'Indonesia',
    quote_en: 'Beautiful weaving and very comfortable. It was easy to ask questions on WhatsApp before ordering.',
    quote_id: 'Anyamannya indah dan sangat nyaman. Mudah bertanya lewat WhatsApp sebelum memesan.',
    rating: 5,
  },
];
